name: job setup
description: 'Sets the shared steps for each job'

inputs:
  node-version:
    description: 'The Node version to be setup'
    required: true
  node-env:
    description: 'Node-Env for CI'
    required: true

runs:
  using: composite
  steps:
    - name: Use Node.js ${{ inputs.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}
    - name: Cache multiple paths
      id: cache-package
      uses: actions/cache@v2
      with:
        path: |
          **/node_modules
        key: ${{ runner.os }}-${{ inputs.node-version }}-${{ hashFiles('**/package.json') }}

    - name: Create dummy config.json
      shell: bash
      run: cp config.json.example config.json

    - name: npm install
      if: steps.cache-package.outputs.cache-hit != 'true'
      shell: bash
      run: |
        npm ci
      env:
        CI: true
        NODE_ENV: ${{ inputs.node-env }}
